### ISSUE TITLE
Titrator SOP To-Do

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#160]
- [ ] Create daily startup procedural checklist (possibly Google Form?) to guide and track usage. Should include:

    1. Checking acid volume.
    2. Checking rinse volume.
    3. Powering system on.
    3. Removing probes from cup in Position 0.
    4. Drying stirrer.
    5. Burette purge.
    6. Re-using acid.
    7. Position 0 contents
    8. pH calibration

- [ ] Create daily shutdown procedural checklist (possibly Google Form?)

   1. Sample disposal.
   2. Probe storage (temp and pH probes).
   3. Powering system down.

- [ ] Create pH meter calibration log file
- [ ] Create pH meter calibration standard curve file (R script and/or Excel file) for equilibration point determination (pH = 3.0 & 3.5)
- [ ] Verbiage for graphing pH meter calibration standard curve
- [ ] Determine sample volume (weight) to use for measurements: 50mL vs. 100mL
- [ ] Automate TA calculations (along with QC checks against standards/previous values)
- [ ] Decide on log/data storage locations (e.g. Google Doc, Owl, Dropbox, etc.)

**Comment by kubu4** [comment]
This issue was moved to RobertsLab/titrator#1
